name: Linter Check

on: [push, pull_request]

jobs:
  lint-python:
    name: Python Linter (Flake8)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: pip install flake8==7.1.2 black

      - name: Run Flake8
        run: flake8 .

  lint-typescript:
    name: TypeScript Linter (ESLint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --max-warnings=0
